version: '3'

services:
  db:
    image: postgres:latest  # Use the latest PostgreSQL image
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8010:5432"  # Map port 5432 on the host to port 5432 on the container
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Check if PostgreSQL is ready
      interval: 10s
      timeout: 5s
      retries: 5


