# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: make build

    - name: Test
      run: make test

  deploy:
      runs-on: ubuntu-latest
      steps:
      - name: 'Create env file'
        run: |
          touch .env
          echo APP_ENV= ${{ vars.APP_ENV }} >> .env
          echo PORT= ${{ vars.DB_PORT }} >> .env
          echo CONTEXT_TIMEOUT= 5 >> .env
          echo DB_HOST= ${{ vars.DB_HOST }} >> .env
          echo DB_PORT= ${{ vars.DB_PORT }} >> .env
          echo DB_USER= ${{ vars.DB_USER }} >> .env
          echo DB_PWD= ${{ vars.DB_PWD }} >> .env
          echo DB_NAME= ${{ vars.DB_NAME }} >> .env
          echo ACCESS_TOKEN_EXPIRY_HOUR = 2 >> .env
          echo REFRESH_TOKEN_EXPIRY_HOUR = 150 >> .env
          echo ACCESS_TOKEN_SECRET= ${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          echo REFRESH_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
          cat .env

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: taskapi
          heroku_email: "hyunbin7303@gmail.com"
          branch: "main"
          delay: 3
